# Generated by Django 4.0.6 on 2022-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
